spring:
  application:
    name: ServiceProvider
  profiles:
    active: peer1

---
spring:
  profiles: peer1

server:
  port: 8672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

sleuth:
  web:
    client:
      enabled: true
  sampler:
    probability: 1.0 #将采样比例设置为1.0，也就是全部都需要。默认是0.1
zipkin:
  base-url: http://localhost:9411
---

spring:
  profiles: peer2

server:
  port: 8627

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

sleuth:
  web:
    client:
      enabled: true
  sampler:
    probability: 1.0 #将采样比例设置为1.0，也就是全部都需要。默认是0.1
zipkin:
  base-url: http://localhost:9411
