server:
  port: 8764


spring:
  application:
    name: RibbonRestTemplate

sleuth:
  web:
    client:
      enabled: true
  sampler:
    probability: 1.0 #将采样比例设置为1.0，也就是全部都需要。默认是0.1
zipkin:
  base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#hystrix:
#  command:
#    default:
#       execution:
#         isolation:
#           thread:
#              timeoutInMilliseconds: 7000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
